### ISSUE TITLE
Keyboard shortcuts awkward on Mac

### ISSUE THREAD

**Issue by sryazanov** [ili-toolbox/ili#7]
Ctrl+up/down interfere with system-wide shortcuts and don't work. Ctrl+S/O is unusual on mac.

**Comment by sryazanov** [comment]
Fedya, please check on Mac. Close this issue if it works fine or assign it back to me if isn't.

**Comment by theodev** [comment]
Ctrl-O works on Mac

Ctrl-S doesn't do anything

Ctrl-up and Ctrl-down work well. The semi-transparent MapSelector is really cool! Can you show it for longer (2 times longer)?

(The shortcut is not perfect because Ctrl-arrows can be reserved for system shortcuts and I used them for Mission Control / Application windows. But ok, I didn't use them so much so for me it's not a problem.)
